const PostActionTypes = {
  POST_COLLECTIONS_START: "POST_COLLECTIONS_START",
  POST_COLLECTIONS_SUCCESS: "POST_COLLECTIONS_SUCCESS",
  POST_COLLECTIONS_FALIURE: "POST_COLLECTIONS_FALIURE"
};
export default PostActionTypes;
